import Head from "next/head";
import { Container, Text, Button } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Text fontSize="2xl">Next.js+ChakraUIのテンプレートです</Text>
        <Button>動的OGP生成</Button>
      </Container>
    </>
  );
}
